export const ledgerNets = [
  'btc',
  'eth',
  'bsc',
  'tez',
  'polkadot',
  'cosmos',
  'osmosis',
  'secret',
  'band',
  'kava',
  'akash',
  'icon',
  'comdex',
  'juno',
  'persistence',
  'chihuahua',
  'sentinel',
  'umee',
  'stargaze',
  'rizon',
  'sifchain',
  'fetch',
  'lum',
  'cheqd',
  'iris',
  'kichain',
  'regen',
  'starname',
  'emoney',
  'cerberus',
  'gbridge',
  'axelar',
  'konstellation',
  'mantle',
  'crescent',
  'orai',
  // 'evmos',
];

export const trezorNets = ['btc', 'eth', 'bsc', 'tez'];

export const keplrNetworksProtobufFormat = ['starname', 'emoney', 'orai'];
export const keplrNetworks = [
  { label: 'Cosmos Hub: cosmoshub-4', key: 'cosmoshub-4', net: 'cosmos' },
  { label: 'Akash: akashnet-2', key: 'akashnet-2', net: 'akash' },
  { label: 'Band: laozi-mainnet', key: 'laozi-mainnet', net: 'band' },
  { label: 'Chihuahua: chihuahua-1', key: 'chihuahua-1', net: 'chihuahua' },
  { label: 'Comdex: comdex-1', key: 'comdex-1', net: 'comdex' },
  { label: 'Juno: juno-1', key: 'juno-1', net: 'juno' },
  { label: 'Kava: kava_2222-10', key: 'kava_2222-10', net: 'kava' },
  { label: 'Osmosis: osmosis-1', key: 'osmosis-1', net: 'osmosis' },
  { label: 'Persistence: core-1', key: 'core-1', net: 'persistence' },
  { label: 'Sentinel: sentinelhub-2', key: 'sentinelhub-2', net: 'sentinel' },
  { label: 'Stargaze: stargaze-1', key: 'stargaze-1', net: 'stargaze' },
  { label: 'Secret: secret-4', key: 'secret-4', net: 'secret' },
  { label: 'Axelar: axelar-dojo-1', key: 'axelar-dojo-1', net: 'axelar' },
  { label: 'Bitsong: bitsong-2b', key: 'bitsong-2b', net: 'bitsong' },
  { label: 'Cheqd: cheqd-mainnet-1', key: 'cheqd-mainnet-1', net: 'cheqd' },
  { label: 'e-Money: emoney-3', key: 'emoney-3', net: 'emoney' },
  { label: 'Evmos: evmos_9001-2', key: 'evmos_9001-2', net: 'evmos' },
  { label: 'Fetch.ai: fetchhub-3', key: 'fetchhub-3', net: 'fetch' },
  // { label: 'Injective: injective-1', key: 'injective-1', net: 'injective' },
  { label: 'Ki Chain: kichain-2', key: 'kichain-2', net: 'kichain' },
  { label: 'Lum: lum-network-1', key: 'lum-network-1', net: 'lum' },
  { label: 'Rizon: titan-1', key: 'titan-1', net: 'rizon' },
  { label: 'Sifchain: sifchain-1', key: 'sifchain-1', net: 'sifchain' },
  { label: 'Umee: umee-1', key: 'umee-1', net: 'umee' },
  { label: 'Regen: regen-1', key: 'regen-1', net: 'regen' },
  { label: 'Iris Network: irishub-1', key: 'irishub-1', net: 'iris' },
  {
    label: 'Starname: iov-mainnet-ibc',
    key: 'iov-mainnet-ibc',
    net: 'starname',
  },
  {
    label: 'Cerberus: cerberus-chain-1',
    key: 'cerberus-chain-1',
    net: 'cerberus',
  },
  { label: 'Konstellation: darchub', key: 'darchub', net: 'konstellation' },
  {
    label: 'Gravity Bridge: gravity-bridge-3',
    key: 'gravity-bridge-3',
    net: 'gbridge',
  },
  { label: 'AssetMantle: mantle-1', key: 'mantle-1', net: 'mantle' },
  { label: 'Crescent: crescent-1', key: 'crescent-1', net: 'crescent' },
  { label: 'Orai: Oraichain', key: 'Oraichain', net: 'orai' },
];
