export const ledgerNets = [
  'btc',
  'eth',
  'bsc',
  'tez',
  'polkadot',
  'cosmos',
  'osmosis',
  'secret',
  'band',
  'kava',
  'akash',
  'icon',
  'comdex',
  'juno',
  'persistence',
  'chihuahua',
  'sentinel',
  'umee',
  'stargaze',
  'rizon',
  'sifchain',
  'fetch',
  'lum',
  'cheqd',
  'iris',
  'kichain',
  'regen',
  'starname',
  'emoney',
  'cerberus',
  'gbridge',
  'axelar',
  'konstellation',
  'mantle',
  'crescent',
  'orai',
  'optimism',
  'arbitrum',
  'polygon',
  'oasis',
  'evmos',
  // 'injective',
  'stafi',
  'stride',
  'tron',
  'jackal',
  'evmoseth',
];

export const metamaskNets = [
  'bsc',
  'eth',
  'polygon',
  'optimism',
  'arbitrum',
  'evmoseth',
];

export const trezorNets = ['btc', 'eth', 'bsc', 'tez'];

export const keplrNetworksProtobufFormat = ['starname', 'emoney', 'orai'];
export const keplrNetworks = [
  { label: 'Cosmos Hub', key: 'cosmoshub-4', net: 'cosmos' },
  { label: 'Akash', key: 'akashnet-2', net: 'akash' },
  { label: 'Band', key: 'laozi-mainnet', net: 'band' },
  { label: 'Chihuahua', key: 'chihuahua-1', net: 'chihuahua' },
  { label: 'Comdex', key: 'comdex-1', net: 'comdex' },
  { label: 'Juno', key: 'juno-1', net: 'juno' },
  { label: 'Kava', key: 'kava_2222-10', net: 'kava' },
  { label: 'Osmosis', key: 'osmosis-1', net: 'osmosis' },
  { label: 'Persistence', key: 'core-1', net: 'persistence' },
  { label: 'Sentinel', key: 'sentinelhub-2', net: 'sentinel' },
  { label: 'Stargaze', key: 'stargaze-1', net: 'stargaze' },
  { label: 'Secret', key: 'secret-4', net: 'secret' },
  { label: 'Axelar', key: 'axelar-dojo-1', net: 'axelar' },
  { label: 'Bitsong', key: 'bitsong-2b', net: 'bitsong' },
  { label: 'Cheqd', key: 'cheqd-mainnet-1', net: 'cheqd' },
  { label: 'e-Money', key: 'emoney-3', net: 'emoney' },
  { label: 'Evmos', key: 'evmos_9001-2', net: 'evmos' },
  { label: 'Fetch.ai', key: 'fetchhub-3', net: 'fetch' },
  { label: 'Injective', key: 'injective-1', net: 'injective' },
  { label: 'Ki Chain', key: 'kichain-2', net: 'kichain' },
  { label: 'Lum', key: 'lum-network-1', net: 'lum' },
  { label: 'Rizon', key: 'titan-1', net: 'rizon' },
  { label: 'Sifchain', key: 'sifchain-1', net: 'sifchain' },
  { label: 'Umee', key: 'umee-1', net: 'umee' },
  { label: 'Regen', key: 'regen-1', net: 'regen' },
  { label: 'Iris Network', key: 'irishub-1', net: 'iris' },
  {
    label: 'Starname',
    key: 'iov-mainnet-ibc',
    net: 'starname',
  },
  {
    label: 'Cerberus',
    key: 'cerberus-chain-1',
    net: 'cerberus',
  },
  { label: 'Konstellation', key: 'darchub', net: 'konstellation' },
  {
    label: 'Gravity Bridge',
    key: 'gravity-bridge-3',
    net: 'gbridge',
  },
  { label: 'AssetMantle', key: 'mantle-1', net: 'mantle' },
  { label: 'Crescent', key: 'crescent-1', net: 'crescent' },
  { label: 'Stride', key: 'stride-1', net: 'stride' },
  { label: 'Stafi', key: 'stafihub-1', net: 'stafi' },
  { label: 'Jackal', key: 'jackal-1', net: 'jackal' },
];

export const showAssetsExep = ['secret', 'bsc'];
